#!/bin/bash                                                                                                                        
##Badjessa B.  Bahoumda                                                                                                             
## CSE 271
## Return the number of commands which share the same inode number                                                                                                                           


cd /usr/bin
declare -a names
declare -a numbers
values=$(ls -i)
for i in $values
do
    if [[ $i =~ ^[0-9]+$ ]];
    then
        numbers+=("$i" )
    fi
done

unsorted_duplicate=$(printf '%s\n' "${numbers[@]}"|awk '!($0 in seen){seen[$0];next} 1')
sorted_duplicates=$(printf "%s\n" "${unsorted_duplicate[@]}" | sort -n)

for j in $sorted_duplicates
do
      temp=$(find -inum "$j" -printf "%f\n" | wc -w)
      echo "$j: $temp commands"
done
